#!/bin/bash

TARGET=/run/k3os/target

source /usr/lib/os-release

# grow()
# {
#     parted $1 resizepart $2 100%
#     partprobe $1
#     sleep 2
#     e2fsck -f $3
#     resize2fs $3
# }

# setup_mounts()
# {
#     mkdir -p $TARGET
#     mount -L K3OS_STATE $TARGET

#     if [ -e $TARGET/k3os/system/growpart ]; then
#         read DEV NUM < $TARGET/k3os/system/growpart
#         if [ ! -e "${DEV}${NUM}" ]; then
#             # /dev/sda2 => /dev/sda2
#             # /dev/nvme0n1p2 => /dev/nvme0n1p2
#             PART=$(blkid -L K3OS_STATE)

#             # /dev/sda2 => /dev/sda
#             # /dev/nvme0n1p2 => /dev/nvme0n1
#             DEV=$(echo "$PART" | sed -r 's/((\d+)p)?\d+$/\2/')

#             # /dev/sda2 => 2
#             # /dev/nvme0n1p2 => 2
#             NUM=$(echo "$PART" | sed 's!.*[^0-9]!!')
#         fi
#         if [ -e "${PART:=${DEV}${NUM}}" ]; then
#             umount $TARGET
#             grow $DEV $NUM $PART || true
#             mount -L K3OS_STATE $TARGET
#         fi
#         rm -f $TARGET/k3os/system/growpart
#     fi
# }

grow() {
    DISK="$1"   # /dev/sda
    NUM="$2"    # 2
    PART="$3"   # /dev/sda2

    echo "Resizing partition $DISK number $NUM ($PART)"

    parted -s "$DISK" resizepart "$NUM" 100% || {
        echo "Failed to resize partition $NUM on $DISK"
        return 1
    }

    # Refresh partition table
    partx -u "$DISK" || partprobe "$DISK"
    udevadm settle
    sleep 2

    # Detect filesystem type
    FSTYPE=$(blkid -o value -s TYPE "$PART")
    echo "Detected filesystem: $FSTYPE"

    case "$FSTYPE" in
        ext2|ext3|ext4)
            echo "Checking and resizing ext filesystem..."
            e2fsck -f "$PART" || return 1
            resize2fs "$PART" || return 1
            ;;
        xfs)
            echo "Growing XFS filesystem..."
            mountpoint=$(findmnt -n -o TARGET "$PART")
            if [ -n "$mountpoint" ]; then
                xfs_growfs "$mountpoint" || return 1
            else
                echo "XFS partition must be mounted to resize."
                return 1
            fi
            ;;
        *)
            echo "Unsupported filesystem type: $FSTYPE"
            return 1
            ;;
    esac

    echo "Filesystem resize complete."
}


setup_mounts() {
    mkdir -p "$TARGET"
    mount -L K3OS_STATE "$TARGET"

    if [ -e "$TARGET/k3os/system/growpart" ]; then
        read DEV NUM < "$TARGET/k3os/system/growpart"

        # Try to determine the correct partition if DEV+NUM is not valid
        if [ ! -e "${DEV}${NUM}" ]; then
            PART=$(blkid -L K3OS_STATE)
            if [[ "$PART" =~ ^(/dev/nvme[0-9]n[0-9])p([0-9]+)$ ]]; then
                DEV="${BASH_REMATCH[1]}"
                NUM="${BASH_REMATCH[2]}"
            elif [[ "$PART" =~ ^(/dev/[a-z]+)([0-9]+)$ ]]; then
                DEV="${BASH_REMATCH[1]}"
                NUM="${BASH_REMATCH[2]}"
            else
                echo "Unable to determine device and partition number from $PART"
                umount "$TARGET"
                return 1
            fi
        fi

        PART="${DEV}${NUM}"

        if [ -e "$PART" ]; then
            echo "Detected partition to grow: $PART"
            umount "$TARGET"
            grow "$DEV" "$NUM" "$PART"
            mount -L K3OS_STATE "$TARGET"
        else
            echo "Partition device $PART does not exist."
        fi

        rm -f "$TARGET/k3os/system/growpart"
    fi
}


setup_kernel_squashfs()
{
    KER_SRC="/.base/k3os/system/kernel/$(uname -r)/kernel.squashfs"
    KER_DEST="$TARGET/k3os/system/kernel/$(uname -r)/kernel.squashfs"
    if [ -e $KER_SRC ] && [ ! -e $KER_DEST ]; then
        mkdir -p $(dirname ${KER_DEST})
        cp -r $KER_SRC $KER_DEST
    fi
}

setup_k3os()
{
    if [ -e $TARGET/k3os/system/k3os/current/k3os ]; then
        return 0
    fi

    K3OS_SRC=/.base/k3os/system/k3os/current/k3os
    K3OS_FILE=$TARGET/k3os/system/k3os/${VERSION_ID}/k3os

    if [ ! -e ${K3OS_SRC} ]; then
        return 0
    fi

    if [ ! -e ${K3OS_FILE} ]; then
        mkdir -p $(dirname ${K3OS_FILE}.tmp)
        cp -f ${K3OS_SRC} ${K3OS_FILE}.tmp
        mv -f ${K3OS_FILE}.tmp ${K3OS_FILE}
    fi

    ln -sf ${VERSION_ID} $TARGET/k3os/system/k3os/current
}

setup_init()
{
    if [ -e $TARGET/sbin/init ]; then
        return 0
    fi

    mkdir -p $TARGET/sbin
    ln -sf ../k3os/system/k3os/current/k3os $TARGET/sbin/init
}

setup_k3s()
{
    if [ -e $TARGET/k3os/system/k3s/current/k3s ]; then
        return 0
    fi

    for i in $(ls -drt $TARGET/k3os/system/k3s/*); do
        if [ ! -L "$i" ]; then
            LATEST=$i
            break
        fi
    done

    if [ -e "${LATEST}" ]; then
        ln -sf $(basename "${LATEST}") $TARGET/k3os/system/k3s/current
        return 0
    fi
}

takeover()
{
    if [ ! -e k3os/system/takeover ]; then
        return 0
    fi

    touch k3os/system/factory-reset

    if [ -L sbin ]; then
      rm -f sbin
    fi

    for i in *; do
        case $i in
            boot|k3os|sbin)
                ;;
            *)
                rm -rf $i
        esac
    done
    for i in sbin/*; do
        case $i in
            sbin/init|sbin/k3s|sbin/k3os)
                ;;
            *)
                rm -rf "$i"
        esac
    done

    rm -rf boot/[^g]*
    rm -f k3os/system/takeover
    rm -rf k3os/data
    sync
    
    if [ -e k3os/system/poweroff ]; then
        rm -f k3os/system/poweroff
        sync
        poweroff -f
    else
        reboot -f
    fi
}

setup_mounts
setup_k3os
setup_kernel_squashfs
setup_init
setup_k3s

cd $TARGET

takeover || true

if [ -e k3os/system/factory-reset ] || [ -e k3os/system/ephemeral ]; then
    rm -rf k3os/data k3os/system/factory-reset
fi

losetup -d /dev/loop0 || true
mount --make-rprivate /
mkdir -p .root
pivot_root . .root
K3OS_MODE=local exec /sbin/init
